name: empty_app
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_math_fork: ^0.7.1
  flutter_tex: ^4.0.3+4
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.3
  mailto: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/uat.jpeg"
  
flutter:
  uses-material-design: true
  assets:
    - lib/assets/
